// +-------------------------------------+
// |        DO NOT EDIT THIS FILE        |
// +-------------------------------------+
// | Please do not edit this file.       |
// | Edit your individual SwiftUI Views. |
// |                                     |
// | Use ⌘-⇧-O to open up the file with  |
// | your name.                          |
// +-------------------------------------+
//
//  AngMoKioView.swift
//  About Us
//
//  Created by Jia Chen Yee on 17/6/22.
//

import SwiftUI

struct AngMoKioView: View {
    var body: some View {
        StudentView(name: "Jasper", view: Jasper())
        StudentView(name: "Elyssa", view: Elyssa())
        StudentView(name: "Jolie", view: Jolie())
        StudentView(name: "Alina", view: Alina())
        StudentView(name: "Comrade Wonho", view: Wonho())
        StudentView(name: "Nicole", view: Nicole())
        StudentView(name: "Daryl", view: Daryl())
    }
}

struct AngMoKioView_Previews: PreviewProvider {
    static var previews: some View {
        AngMoKioView()
    }
}
