// +-------------------------------------+
// |        DO NOT EDIT THIS FILE        |
// +-------------------------------------+
// | Please do not edit this file.       |
// | Edit your individual SwiftUI Views. |
// |                                     |
// | Use ⌘-⇧-O to open up the file with  |
// | your name.                          |
// +-------------------------------------+
//
//  WoodlandsView.swift
//  About Us
//
//  Created by Jia Chen Yee on 17/6/22.
//

import SwiftUI

struct WoodlandsView: View {
    var body: some View {
        StudentView(name: "Xinyi", view: Xinyi())
        StudentView(name: "Comrade Hao Yuan", view: HaoYuan())
        StudentView(name: "Kai Qi", view: KaiQi())
        StudentView(name: "Kaitlyn", view: Kaitlyn())
        StudentView(name: "Faith", view: Faith())
        StudentView(name: "Sairam", view: Sairam())
        StudentView(name: "Daniel", view: Daniel())
    }
}

struct WoodlandsView_Previews: PreviewProvider {
    static var previews: some View {
        WoodlandsView()
    }
}
