// +-------------------------------------+
// |        DO NOT EDIT THIS FILE        |
// +-------------------------------------+
// | Please do not edit this file.       |
// | Edit your individual SwiftUI Views. |
// |                                     |
// | Use ⌘-⇧-O to open up the file with  |
// | your name.                          |
// +-------------------------------------+
//
//  StevensView.swift
//  About Us
//
//  Created by Jia Chen Yee on 17/6/22.
//

import SwiftUI

struct StevensView: View {
    var body: some View {
        StudentView(name: "Niutian", view: Niutian())
        StudentView(name: "Isaac", view: Isaac())
        StudentView(name: "Ethan", view: Ethan())
        StudentView(name: "Xin Xuan", view: XinXuan())
        StudentView(name: "Vanisha", view: Vanisha())
        StudentView(name: "Rachel", view: Rachel())
        StudentView(name: "Geoffrey", view: Geoffrey())
        StudentView(name: "Haoming", view: Haoming())
    }
}

struct StevensView_Previews: PreviewProvider {
    static var previews: some View {
        StevensView()
    }
}
