// +-------------------------------------+
// |        DO NOT EDIT THIS FILE        |
// +-------------------------------------+
// | Please do not edit this file.       |
// | Edit your individual SwiftUI Views. |
// |                                     |
// | Use ⌘-⇧-O to open up the file with  |
// | your name.                          |
// +-------------------------------------+
//
//  OneNorthView.swift
//  About Us
//
//  Created by Jia Chen Yee on 17/6/22.
//

import SwiftUI

struct OneNorthView: View {
    var body: some View {
        StudentView(name: "Comrade Chloe", view: Chloe())
        StudentView(name: "Aaron", view: Aaron())
        StudentView(name: "Zhiyu", view: Zhiyu())
        StudentView(name: "Katelyn", view: Katelyn())
        StudentView(name: "Felix", view: Felix())
        StudentView(name: "Kai Quan", view: KaiQuan())
        StudentView(name: "Daniyal", view: Daniyal())
    }
}

struct OneNorthView_Previews: PreviewProvider {
    static var previews: some View {
        OneNorthView()
    }
}
