// +-------------------------------------+
// |        DO NOT EDIT THIS FILE        |
// +-------------------------------------+
// | Please do not edit this file.       |
// | Edit your individual SwiftUI Views. |
// |                                     |
// | Use ⌘-⇧-O to open up the file with  |
// | your name.                          |
// +-------------------------------------+
//
//  GulCircleView.swift
//  About Us
//
//  Created by Jia Chen Yee on 17/6/22.
//

import SwiftUI

struct GulCircleView: View {
    var body: some View {
        StudentView(name: "Kate Lynn", view: KateLynn())
        StudentView(name: "Angus", view: Angus())
        StudentView(name: "Regina", view: Regina())
        StudentView(name: "Yun Jun", view: YunJun())
        StudentView(name: "Guan Yi", view: GuanYi())
        StudentView(name: "Yap Tong", view: YapTong())
        StudentView(name: "Nethan", view: Nethan())
    }
}

struct GulCircleView_Previews: PreviewProvider {
    static var previews: some View {
        GulCircleView()
    }
}
