// +-------------------------------------+
// |        DO NOT EDIT THIS FILE        |
// +-------------------------------------+
// | Please do not edit this file.       |
// | Edit your individual SwiftUI Views. |
// |                                     |
// | Use ⌘-⇧-O to open up the file with  |
// | your name.                          |
// +-------------------------------------+
//
//  NewtonView.swift
//  About Us
//
//  Created by Jia Chen Yee on 17/6/22.
//

import SwiftUI

struct NewtonView: View {
    var body: some View {
        StudentView(name: "Dishita", view: Dishita())
        StudentView(name: "Alpheus", view: Alpheus())
        StudentView(name: "Comrade Yuhan", view: Yuhan())
        StudentView(name: "Jun Heng", view: JunHeng())
        StudentView(name: "Jing Xian", view: JingXian())
        StudentView(name: "Ryan", view: Ryan())
        StudentView(name: "Zachary", view: Zachary())
    }
}

struct NewtonView_Previews: PreviewProvider {
    static var previews: some View {
        NewtonView()
    }
}
