// +-------------------------------------+
// |        DO NOT EDIT THIS FILE        |
// +-------------------------------------+
// | Please do not edit this file.       |
// | Edit your individual SwiftUI Views. |
// |                                     |
// | Use ⌘-⇧-O to open up the file with  |
// | your name.                          |
// +-------------------------------------+
//
//  YJ.swift
//  About Us
//
//  Created by Jia Chen Yee on 17/6/22.
//

import SwiftUI

struct YJ: View {
    var body: some View {
        VStack {
            Text("YJ")
            Text("[My favourite characters](https://www.youtube.com/watch?v=1UdI_eoDPKQ)")
        }
    }
}

struct YJ_Previews: PreviewProvider {
    static var previews: some View {
        YJ()
    }
}
