// +-------------------------------------+
// |        DO NOT EDIT THIS FILE        |
// +-------------------------------------+
// | Please do not edit this file.       |
// | Edit your individual SwiftUI Views. |
// |                                     |
// | Use ⌘-⇧-O to open up the file with  |
// | your name.                          |
// +-------------------------------------+
//
//  StudentView.swift
//  About Us
//
//  Created by Jia Chen Yee on 17/6/22.
//

import SwiftUI

struct StudentView<Content: View>: View {
    var name: String
    var view: Content
    
    var body: some View {
        NavigationLink(name) {
            view
        }
        .disabled(String(describing: type(of: view.body)) == "Text")
    }
}

struct StudentView_Previews: PreviewProvider {
    static var previews: some View {
        StudentView(name: "Test", view: Text("Hello"))
    }
}
